apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart-museum
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    path: k8s/argocd-deploy/chart-museum
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: registries
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  ignoreDifferences:
    - kind: Deployment
      group: apps
      jsonPointers:
        - /spec/replicas
