apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: distribution
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    path: k8s/argocd-deploy/distribution
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: registries
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

  ignoreDifferences:
    - kind: Secret
      jqPathExpressions:
        - .data.haSharedSecret

    - kind: Deployment
      group: apps
      jqPathExpressions:
        - .spec.template.metadata.annotations["checksum/config"]
        - .spec.template.metadata.annotations["checksum/secret"]
