apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate-connector
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    path: k8s/argocd-deploy/twingate-connector
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: twingate-connector
  syncPolicy:
    automated:
      # allow scale down
      selfHeal: false
      prune: true
    syncOptions:
      - CreateNamespace=true
