apiVersion: v1
name: nextcloud
version: 1.0.0
description: nextcloud wrapper chart
type: application

dependencies:
  - name: nextcloud
    version: ~8.5
    repository: https://nextcloud.github.io/helm/

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress

  - name: valkey
    version: ~0.7
    repository: https://valkey.io/valkey-helm/

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth

