apiVersion: 1.0.0
name: gogs
version: 0.0.1
description: gogs wrapper chart
type: application

dependencies:
  - name: gogs
    repository: https://chr0n1x.github.io/gogs-helm-chart
    version: 0.0.3

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
