traefik-ingress:
  dnsNames:
    - dns: gogs.rannet.duckdns.org
      services:
        - kind: Service
          name: gogs-svc
          port: http

gogs:
  persistence:
    enabled: true
    size: 2Gi
    storageClass: longhorn
    existingVolumeName: pvc-64c3266e-968d-4147-99af-b0cd7325b873
