traefik-ingress:
  dnsNames:
    - dns: gogs.rannet.duckdns.org
      services:
        - kind: Service
          name: gogs-svc
          port: http

cnpg:
  image: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3
  size: 2Gi
  storageClass: longhorn
  roleName: gogs

gogs:
  deployment:
    extraEnvVars:
      - name: DATABASE_TYPE
        value: postgres
      - name: DATABASE_HOST
        value: gogs-rw:5432
      - name: DATABASE_USER
        valueFrom:
          secretKeyRef:
            name: gogs-superuser
            key: username
      - name: DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: gogs-superuser
            key: password

  persistence:
    enabled: true
    size: 2Gi
    storageClass: longhorn
    # existingVolumeName: pvc-64c3266e-968d-4147-99af-b0cd7325b873
