apiVersion: v1
name: paperless-ngx
version: 1.0.0
description: paperless-ngx wrapper chart
type: application

dependencies:
  - name: paperless-ngx
    version: ~0.24
    repository: https://charts.gabe565.com

  - name: valkey
    version: ~0.7
    repository: https://valkey.io/valkey-helm/

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress

  - name: keda-global-cron
    version: ~1
    repository: file://../../helm/keda-global-cron
