apiVersion: 1.0.0
name: homepage
version: 1.0.0
description: homepage wrapper chart
type: application

dependencies:
  - name: homepage
    version: ~2
    repository: https://jameswynn.github.io/helm-charts

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth
