apiVersion: 1.0.0
name: vault
version: 1.0.0
description: |
  hashi-corp vault wrapper chart
  meant ONLY for intra-service secrets
  NOT PRODUCTION GRADE
type: application

dependencies:
  - name: vault
    version: ~0
    repository: https://helm.releases.hashicorp.com

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
