apiVersion: 1.0.0
name: grafana
version: 1.0.0
description: grafana wrapper chart
type: application

dependencies:
  - name: grafana
    version: ~11
    repository: https://grafana-community.github.io/helm-charts

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
