apiVersion: 1.0.0
name: grafana
version: 1.0.0
description: grafana wrapper chart
type: application

dependencies:
  - name: grafana
    version: ~8.13
    repository: https://grafana.github.io/helm-charts

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth
