---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tandoor-oidc-secrets-vaultsecret-ref
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  path: tandoor/env
  destination:
    name: tandoor-env
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Release.Namespace -}}/tandoor-vso-connection-auth
