vault-auth:
  vaultConnectionName: vault-secrets-operator/default
  authMethods:
    - name: on-prem
      # match this up with secret
      vaultAuthName: smb-csi-vso-connection-auth
      method: kubernetes
      mount: in-cluster
      config:
        role: smb-csi
        serviceAccount: csi-smb-controller-sa
        audiences:
          - vault

smb:
  # remember to replace this with something real
  hostShare: //nas.lan/k8s.smb-csi-share
