apiVersion: 1.0.0
name: prometheus
version: 1.0.0
description: prometheus wrapper chart
type: application

dependencies:
  - name: prometheus
    version: ~28
    repository: https://prometheus-community.github.io/helm-charts

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
