---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  # not sure if this works anymore
  annotations:
    cert-manager.io/cluster-issuer: duckdns-letsencrypt-prod
  name: homepage-traefik-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - kind: Rule
    match: Host(`rannet.duckdns.org`) && PathRegexp(`.*`)
    services:
    - kind: Service
      name: homepage
      port: http
  tls:
    domains:
    - main: rannet.duckdns.org
    secretName: homepage-cert
