{{- range $email := .Values.adminEmails -}}
{{- $emailParts := (split "@" $email) -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin-{{ $emailParts._0 }}
  namespace: {{ $.Release.Namespace }}
subjects:
  - kind: User
    name: {{ $email }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ $.Values.headlamp.clusterRoleBinding.clusterRoleName | default "cluster-admin" }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
