---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-cert-manager-ref
  namespace: {{ .Release.Namespace }}
spec:
  secretName: traefik-dashboard-cert
  dnsNames:
    - "traefik.rannet.duckdns.org"
  issuerRef:
    kind: ClusterIssuer
    name: duckdns-letsencrypt-prod
