apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: {{ .Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repo.url }}
    path: k8s/argocd-deploy/traefik
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../values.yaml
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik

  ignoreDifferences:
    - kind: Deployment
      jsonPointers:
        # REEEEEEE
        - /spec/template/metadata/annotations/prometheus.io~1port

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # then add to labels:
      #   pod-security.kubernetes.io/audit: privileged
      #   pod-security.kubernetes.io/enforce: privileged
      #   pod-security.kubernetes.io/warn: privileged
