apiVersion: 1.0.0
name: cert-manager
version: 1.0.0
description: wrapper chart for cert-manager
type: application

dependencies:
  # installation & uninstallation instructions:
  # https://cert-manager.io/docs/installation/helm/#installing-with-helm 
  - name: cert-manager
    version: ~1.17
    repository: https://charts.jetstack.io

  - name: cert-manager-duckdns-webhook
    version: ~1.1
    repository: https://csp33.github.io/cert-manager-duckdns-webhook

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth
