apiVersion: 1.0.0
name: argocd
version: 1.0.0
description: argocd wrapper chart
type: application

dependencies:
  - name: argo-cd
    version: ~9
    repository: https://argoproj.github.io/argo-helm

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth
