---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gogs
  namespace: {{ .Release.Namespace }}
spec:
  imageName: {{ .Values.cnpg.image }}
  instances: {{ .Values.cnpg.instances | default 1 }}

  enableSuperuserAccess: true

  managed:
    roles:
      - name: {{ .Values.cnpg.roleName }}
        superuser: true
        login: true
        passwordSecret:
          name: gogs-postgres-user

  bootstrap:
    initdb:
      database: gogs
      owner: gogs
      secret:
        name: gogs-postgres-user
  storage:
    {{- with .Values.cnpg.size }}
    size: {{ . }}
    {{- end }}

    {{- with .Values.cnpg.storageClass }}
    storageClass: {{ . }}
    {{- end }}
