apiVersion: v1
name: ollama
version: 1.0.0
description: open-webui and ollama wrapper chart
type: application

dependencies:
  - name: open-webui
    version: ~10
    repository: https://helm.openwebui.com/

  - name: vault-auth
    version: ~1
    repository: file://../../helm/vault-auth

  - name: valkey
    version: ~0.7
    repository: https://valkey.io/valkey-helm/

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
