apiVersion: 1.0.0
name: authentik
version: 1.0.0
description: authentik wrapper chart
type: application

dependencies:
  - name: authentik
    version: ~2025
    repository: https://charts.goauthentik.io

  - name: valkey
    version: ~0.7
    repository: https://valkey.io/valkey-helm/

  - name: keda-global-cron
    version: ~1
    repository: file://../../helm/keda-global-cron
