apiVersion: 1.0.0
name: searxng
version: 1.0.0
description: searxng wrapper chart
type: application

dependencies:
  - name: searxng
    version: ~1
    repository: https://chr0n1x.github.io/searxng-helm-chart

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
