---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: env-secrets-vaultsecret-ref
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  path: cert-manager/duckdns
  destination:
    name: cert-manager-cert-manager-duckdns-webhook
    create: true
    overwrite: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Release.Namespace -}}/cert-manager-vso-connection-auth
