apiVersion: 1.0.0
name: chart-museum
version: 1.0.0
description: chart-museum wrapper chart
type: application

dependencies:
  - name: chartmuseum
    version: ~3
    repository: https://chartmuseum.github.io/charts

  - name: valkey
    version: ~0.7
    repository: https://valkey.io/valkey-helm/

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
