apiVersion: 1.0.0
name: chart-museum
version: 1.0.0
description: chart-museum wrapper chart
type: application

dependencies:
  - name: chart-museum
    version: ~3
    repository: https://chartmuseum.github.io/charts

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
