---
apiVersion: 1.0.0
name: mealie
version: 0.0.1
description: simple mealie installation
type: application

dependencies:
  - name: mealie
    repository: https://chr0n1x.github.io/mealie-helm-chart
    version: ~0.0.0

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress
