apiVersion: 1.0.0
name: immich
version: 1.0.0
description: immich wrapper chart
type: application

dependencies:
  - name: immich
    version: ~0.10
    repository: https://immich-app.github.io/immich-charts

  - name: valkey
    version: ~0.7
    repository: https://valkey.io/valkey-helm/

  - name: traefik-ingress
    version: ~1
    repository: file://../../helm/traefik-ingress

  - name: keda-global-cron
    version: ~1
    repository: file://../../helm/keda-global-cron
