apiVersion: 1.0.0
name: immich
version: 1.0.0
description: immich wrapper chart
type: application

dependencies:
  - name: immich
    version: ~0.9
    repository: https://immich-app.github.io/immich-charts

  - name: valkey
    version: ~0.7
    repository: https://valkey.io/valkey-helm/
