global:
  # https://keda.sh/docs/2.18/scalers/cron/#scale-to-0-during-off-hours
  cooldownPeriod: 300
  # actual scale to 0
  minReplicaCount: 0
  tz: EST
  start: "0 9 * * *"
  end: "0 22 * * *"
  # IMPORTANT: must be string :/
  desiredReplicas: "1"

objects:
  - name: deployment-1
    cooldownPeriod: 150 
    cron:
      tz: Asia/Kolkata
      start: "0 0 * * *"
      end: "0 1 * * * *"
      desiredReplicas: "3"

  # default to single cron in EST, from 9AM to 10PM, that scales
  # "deployment-est" up to 1
  - name: deployment-est

  - name: deployment-custom
    # same as keda.sha.v1alpha/ScaledObject.spec.triggers
    triggers:
      - type: cron
        metadata:
          tz: Asia/Japan
          start: "0 0 * * *"
          end: "0 1 * * * *"
          desiredReplicas: "5"
