---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: env-secrets-vaultsecret-ref
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  path: ollama/env
  destination:
    name: env-secrets
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Release.Namespace -}}/ollama-vso-connection-auth
