---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-secrets-vaultsecret-ref
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  path: ollama/oidc/authentik
  destination:
    name: oidc-authentik-secrets
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Release.Namespace -}}/ollama-vso-connection-auth
