---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name -}}-cert-manager-ref
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-cert
  dnsNames:
    {{- range $cfg := .Values.dnsNames }}
    - {{ $cfg.dns }}
    {{- end }}
  {{- with .issuerRef }}
  issuerRef:
    kind: {{ .kind | default "ClusterIssuer" }}
    name: {{ .name | default "duckdns-letsencrypt-prod" }}
  {{- end }}
