# TODO: rename this
apiVersion: 1.0.0
name: descheduler
version: 1.0.0
description: wrapper chart w/ policies for various cleanup services
type: application

dependencies:
  - name: descheduler
    version: ~0
    repository: https://kubernetes-sigs.github.io/descheduler/
