---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitea-oidc-secrets-vaultsecret-ref
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: in-cluster
  path: gitea/oidc
  destination:
    name: authentik-oidc-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: {{ .Release.Namespace -}}/gitea-vso-connection-auth
